-- This reconciliation migration was generated from a drifted database and
-- duplicated changes already applied by earlier migrations. It is intentionally
-- a no-op so a fresh `prisma migrate deploy` can replay the migration history.
--
-- The duplicated operations were:
-- - removing Basket (already done in 20260515000000_remove_basket)
-- - package-expiry and query indexes (already done in
--   20260519000000_db_audit_fixes)
